#ifndef SONIC_ANYWHERE_SPRITE_MAPPING_TYPE_H
#define SONIC_ANYWHERE_SPRITE_MAPPING_TYPE_H

typedef enum S1SpriteMappingType {
    S1_SPRITE_MAPPING_TYPE__CREDITS
} S1SpriteMappingType;

#endif // SONIC_ANYWHERE_SPRITE_MAPPING_TYPE_H
